apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-cliente-deployment
  labels:
    app: api-cliente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-cliente
  template:
    metadata:
      labels:
        app: api-cliente
    spec:
      containers:
        - name: api-cliente-container
          image: u2dtecnologia/api-cliente
          ports:
            - containerPort: 8080
