apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente-deployment
  labels:
    app: cliente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cliente
  template:
    metadata:
      labels:
        app: cliente
    spec:
      containers:
        - name: cliente-container
          image: u2dtecnologia/cliente
          ports:
            - containerPort: 8080
