server:
  servlet:
    context-path: /api
  port: 8080

spring:
  application:
    name: api-cliente
  profiles:
    active: tst
  security:
    user:
      name: builder
      password: builder
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cliente
    username: postgres
    password: postgres
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    enabled: true
    changeLog: classpath:db/changelog/db.changelog-master.yaml
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      fail-on-empty-beans: false

